name: Review

on:
  pull_request:
    types: [ opened, synchronize ]
    branches: [ main ]

jobs:
  review:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      # リポジトリのチェックアウト
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      # reviewdog で ESLint のエラーをチェック
      - name: Run lint and reviewdog
        uses: reviewdog/action-eslint@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workdir: functions
          reporter: github-pr-review 
          level: warning
          eslint_flags: 'src/**/*'

      - name: TEST Run eslint command
        run: |
          cd functions
          npm run lint
