name: Review

on:
  pull_request:
    types: [ opened, synchronize ]
    branches: [ main ]

jobs:
  review:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      # リポジトリのチェックアウト
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Node.js のセットアップ
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node-version }}
      
      # 依存パッケージをインストール
      - name: Install dependency packages
        run: |
          cd functions
          npm install
      
      # reviewdog で ESLint のエラーをチェック
      - name: Run lint and reviewdog
        uses: reviewdog/action-eslint@v1
        with:
          github_token: ${{ secrets.github_token }}
          workdir: './functions'
          reporter: github-pr-review 
          level: warning
          eslint_flags: 'src/**/*'
