name: Review

on:
  pull_request:
    types: [ opened, synchronize ]
    branches: [ main ]

jobs:
  review:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      # リポジトリのチェックアウト
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Node.js のセットアップ
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node-version }}

      # 依存パッケージをインストール
      - name: Install dependency packages
        run: |
          cd functions
          npm install
      
      # reviewdog のセットアップ
      - name: Setup reviewdog
        uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest

      - name: Run tsc with reviewdog
        run: |
          cd functions
          tsc --pretty false --noEmit | reviewdog -f=tsc -reporter=github-pr-review -fail-on-error=true
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}